### ISSUE TITLE
Playground release as a package checklist

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1842]
## Checklist

- [ ] Make sure it can be consumed as a react component without needing the vite plugin 
- [x] Split into 2 packages: 
 - `@typespec/playground ` Playground components and utils
 - `@typespec/playground-website` our playground

Make sure the following are accessible from the root

- [x] `import { createBrowserHost } from '@typespec/playground/src/browser-host.js';`
- [x] `import { StyledPlayground} from "@typespec/playground/src/components/playground.js";`
- [x] `import { attachServices } from "@typespec/playground/src/services.js";`
- [x] `import { getTypeSpecContentFromQueryParam, saveTypeSpecContentInQueryParameter } from "@typespec/playground/src/state-storage.js";`

Those have gotten new apis instead.

Cut, this one should not be needed
- [x] `import "@typespec/playground/src/style.css";`

```[tasklist]
### Tasks
- [x] Split packages Split playground package #1965
- [x] Remove recoil [Playground pkg] Remove recoil #2011
- [x] Remove internal use of playground manifest and expose as options Playground remove use of manifest internally  #2019
- [x] Improve the url save state helper(should be able to save more state easily, like selected emitter) Playground: Provide a more reusable storage state #2103
- [ ] Make sure the bundler can be used independently too
- [x] Ensure all checklist points above are accesible
- [x] Write docs and tests
- [x] Release and let teams try it out with note that it is experimental and might break
```

**Comment by timotheeguerin** [comment]
This is done
