### ISSUE TITLE
Public Beta site

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/typespec#2252]
With the expected stylesheet and layout provided by designer Crystal, let's start modeling it in Docusaurus.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/typespec/issues/2287
- [ ] https://github.com/microsoft/typespec/issues/2292
- [ ] Investigate Ignite announcement process/requirements
```

**Comment by markcowl** [comment]
Completed!
