### ISSUE TITLE
Wrap up redesigns for public site

### ISSUE THREAD

**Issue by ccbarragan** [microsoft/typespec#2287]
Part of https://github.com/microsoft/typespec/issues/2151. Finalize phase 1 design work for public TypeSpec website.

**Tasks**

- [x] Refine designs based on feedback from team
- [x] Review with Foundations design team for alignment
- [x] Hand off to development (design files, illustration assets)

**Resources**
[Design files](https://www.figma.com/file/8iipnzLVistMDEC1sg6Evh/TypeSpec-website?type=design&node-id=6%3A441&mode=design&t=1TRyQQCnCdcnDzok-1)

**Comment by ccbarragan** [comment]
Also needed: Style updates to existing Docusaurus pages so that they align better with incoming designs.

- Background / foreground colors
- Accent colors
- Corner radius
- Font family
- Footer
