### ISSUE TITLE
Make handling of empty object consistent in request/response body

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2868]
Design https://github.com/microsoft/typespec/issues/2513

1. Introduce new decorators and repurpose some

- `@body` => `@bodyRoot` in its current meaning
- `@body` => now means actual body. Nothing inside of this can be metadata(header, query, etc.)
- `@bodyIgnore` => provide a way to ignore a property from the body

2. If the resulting body is `{}` after removing all ignored properties then the body is `void`
3. Status code is always 200 unless the body is explicitly `void` then it is 204 (Or do we want to always make it 200)

```[tasklist]
### Tasks
- [x] Rename `@body` -> `@bodyRoot`
- [x] Add `@body` as an explicit body meaning
- [ ] Add `@bodyIgnore`
- [x] Had helper in http library to resolve the body correctly according to the ` If the resulting body is `{}` after removing all ignored properties then the body is `void`
- [ ] Make sure status code is always 200 unless `op foo(): void`
- [ ] Check openapi and autorest emitters use the http api
- [ ] Check tcgc is doing things correctly and work with other emitters to be sure they do
```
