### ISSUE TITLE
[Epic] Feature Gap between OpenAPI 3.0 Emitter and OpenAPI 3.0 Specification

### ISSUE THREAD

**Issue by wanlwanl** [microsoft/typespec#3836]
It's a issue to track feature gap between typespec OAS3 emitter and OAS3, it's not a ask.

```[tasklist]
### Bugs
- [ ] https://github.com/microsoft/typespec/issues/3885
- [ ] https://github.com/microsoft/typespec/issues/3887
- [ ] https://github.com/microsoft/typespec/issues/4097
- [ ] https://github.com/microsoft/typespec/issues/4584
- [ ] https://github.com/microsoft/typespec/issues/4707
- [ ] https://github.com/microsoft/typespec/issues/3889
- [ ] https://github.com/microsoft/typespec/issues/4869
```

```[tasklist]
### Not Supported Features
- [ ] https://github.com/microsoft/typespec/issues/3926
- [ ] https://github.com/microsoft/typespec/issues/3928
- [ ] https://github.com/microsoft/typespec/issues/3925
- [ ] https://github.com/microsoft/typespec/issues/3945
- [ ] Failed to limit by template type: https://github.com/joseharriaga/openai-in-typespec/pull/161/files#diff-c20be432499dab9965f03acd95280668d4ddf939c32878fd6a17a0048ecf6690
- [ ] https://github.com/microsoft/typespec/issues/4511
- [ ] https://github.com/microsoft/typespec/issues/4321
- [ ] https://github.com/microsoft/typespec/issues/3293
- [ ] https://github.com/microsoft/typespec/issues/2220
```

**Comment by markcowl** [comment]
@wanlwanl please fill in details of the ask

**Comment by skywing918** [comment]
@extension failed to add specification extension

## Actual Specification

``` json 
The OpenAPI Object cannot be extended with Specification Extensions.

``` 

## Expected Specification


``` json 
The OpenAPI Object be extended with Specification Extensions.

```

**Comment by wanlwanl** [comment]
Updated

**Comment by skywing918** [comment]
OpenAPI 3 Emitter failed to add specification extension in root
https://github.com/microsoft/typespec/issues/3870

OpenAPI 3 Emitter failed to define a webhooks in root -- oas v3.1.0
https://github.com/microsoft/typespec/issues/3882

OpenAPI 3 Emitter failed to define a jsonSchemaDialect in root -- oas v3.1.0
https://github.com/microsoft/typespec/issues/3883

**Comment by bterlson** [comment]
I think we should be clearly separating features in 3.1 which we do not support intentionally (and thus are feature requests not bugs) and things which impact 3.0 which we do target.

**Comment by qiaozha** [comment]
test comment

**Comment by wanlwanl** [comment]
Sure. Let's focus on 3.0 @skywing918

**Comment by skywing918** [comment]
• OpenAPI 3 Emitter failed to check type of termsOfService in @info
https://github.com/microsoft/typespec/issues/3885


• @info decorator failed to exclude unallow keys, it only allow fixed fields and start with "x-".
https://github.com/microsoft/typespec/issues/3887


• @server decorator failed to generate without description.

https://github.com/microsoft/typespec/issues/3924
	
	
•  Path Item object not support fields Summary/description/parameters 

https://github.com/microsoft/typespec/issues/3925


• operation object not support fields Callbacks/security 

https://github.com/microsoft/typespec/issues/3926

	
• Parameter object not support fields allowEmptyValue/deprecated/example/examples/content
https://github.com/microsoft/typespec/issues/3928
	
	
• Response object not support field links
https://github.com/microsoft/typespec/issues/3927
	
	
• @tag decorator not support tag object
https://github.com/microsoft/typespec/issues/3923

**Comment by wanlwanl** [comment]
Use https://github.com/orgs/Azure/projects/142/views/1 to track OAS 3 emitter issues in the future
