### ISSUE TITLE
[Bug]: OpenAPI 3 Emitter failed to add specification extension in objects

### ISSUE THREAD

**Issue by skywing918** [microsoft/typespec#3941]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/typespec/issues/3870
- [ ] https://github.com/microsoft/typespec/issues/3939
- [ ] https://github.com/microsoft/typespec/issues/3940
- [ ] https://github.com/microsoft/typespec/issues/3942
```
