### ISSUE TITLE
Opt into chronus changelog tracking for Java emitter

### ISSUE THREAD

**Issue by srnagar** [microsoft/typespec#3962]
### Clear and concise description of the problem

Opting out of change sets from chronus for the initial migration of Java emitter to this repo. We'll opt in to this once we moved everything over to this repo.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
@srnagar are you starting the migration to this repo, assume more issue are comming do you need a new issue label?
See https://github.com/microsoft/typespec/blob/main/CONTRIBUTING.md#updating-labels to add a new one

**Comment by srnagar** [comment]
@timotheeguerin yes, I have started the migration and is currently in my fork. I will be filing more issues as needed. Could you please create a new label for Java emitter - `emitter:client:java`?

**Comment by timotheeguerin** [comment]
java uses chronus now
