### ISSUE TITLE
Support multiple namespaces in client library code generation

### ISSUE THREAD

**Issue by srnagar** [microsoft/typespec#4537]
### Clear and concise description of the problem

Currently, code generators for .NET, Java and Python only support generating client library in a single namespace. Generators use the namespace defined in tspconfig.yaml and ignore the namespaces defined in TypeSpec. This works when we only have a single namespace. 

However, there are cases where we need multiple namespaces in the generated library to allow different clients to be in different namespaces (for e.g. OpenAI and Search). So, the proposal is for generators to use the namespaces defined in TypeSpec as the namespaces in client libraries too and not use tspconfig.yaml.

More details on the proposal can be found [here](https://gist.github.com/srnagar/a695faa1a4d8a5dbf44af826f05916f0).

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Spec
- [ ] https://github.com/Azure/cadl-ranch/issues/758
- [ ] https://github.com/Azure/typespec-azure/issues/1722

### Implementation
- [ ] https://github.com/Azure/typespec-azure/issues/1723
- [ ] https://github.com/Azure/autorest.java/issues/2968
- [ ] https://github.com/Azure/autorest.typescript/issues/2877
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/47670
- [ ] https://github.com/Azure/autorest.go/issues/1452
- [ ] https://github.com/Azure/autorest.cpp/issues/404
- [ ] https://github.com/Azure/typespec-rust/issues/130
- [ ] https://github.com/Azure/autorest.python/issues/2795
- [ ] https://github.com/Azure/typespec-azure/issues/1604

**Comment by lirenhe** [comment]
To clarify, we need to support multiple namespaces also for unbranded scenario and the scope includes c#, Java, Python, JS Modular

**Comment by weidongxu-microsoft** [comment]
There is models under `typespec.rest.resource`, e.g. https://github.com/microsoft/typespec/blob/main/packages/rest/lib/resource.tsp#L115-L117

For now, unbranded won't do any mapping from typespec namespace, so they would appear at
https://github.com/allenjzhang/typespec-e2e-demo/blob/main/petstore/clients/java/src/main/java/typespec/rest/resource/PetUpdate.java

Do we need to do a mapping?

**Comment by iscai-msft** [comment]
python has added support for this in our latest generator, so removing the python label

**Comment by lmazuel** [comment]
Closing as done for T1 languages
