### ISSUE TITLE
[Unbranded Client CodeGen] We could generate client SDK without tspconfig.yaml

### ISSUE THREAD

**Issue by lirenhe** [microsoft/typespec#5201]
### Clear and concise description of the problem

Please verify whether we could generate code without tspconfig.yaml and we need to support this.  
The SDK generation should use the default config settings.  

```[tasklist]
### Verify & Fix
- [ ] https://github.com/Azure/autorest.python/issues/2933
- [ ] https://github.com/Azure/autorest.csharp/issues/5181
- [ ] https://github.com/Azure/autorest.java/issues/2989
- [ ] https://github.com/Azure/autorest.typescript/issues/2930
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://typespec.io/docs/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JoshLove-msft** [comment]
tspconfig.yaml is not required for generation as evidenced by our cadl-ranch tests.
