### ISSUE TITLE
Language Integrity

### ISSUE THREAD

**Issue by markweitzel** [microsoft/typespec#899]
Be able to determine when the language itself introduces breaking change

**Comment by mikekistler** [comment]
Ideally all language breaking changes would be detected by a test suite. Is our current test suite sufficient or are there gaps we should address?

It would be good to analyze breaking changes over several releases (either backward or forward) to see which ones were caught by the test suite vs would have slipped through.

**Comment by allenjzhang** [comment]
> Is our current test suite sufficient or are there gaps we should address?

Our code coverage is pretty high. Do we need to define a new bar. We can take this item as assess current unit tests and evaluate if additional coverage/bar is needed.

**Comment by allenjzhang** [comment]
[Coverage report as of 9/27.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1879101&view=codecoverage-tab)

- [ ] cadl-azure-resource-manager.src -> common_types
- [ ] cadl-azure-core.src -> decorators.ts
- [ ]  cadl-azure-language.src -> internal-decorators.ts
- [ ]  cadl-azure-resource-manager.src -> internal.ts

**Comment by allenjzhang** [comment]
#908

**Comment by allenjzhang** [comment]
While unit tests give good coverage of scenarios, the sample size is smaller. We can have a process that runs cadl against all checked-in files in spec repo and report breakages. Investigate whether Cadl Ranch can be updated for reporting breakages or some other reporting portal.

**Comment by allenjzhang** [comment]
As we formalize the rest-spec repo automation, this can occur in the March sprint or later with the infra team's help.
